### ISSUE TITLE
Track Polkadot releases in its own branch

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#1085]
Instead of committing the latest Polkadot full release version to `main` as implemented in #930, create a dedicated branch for tracking Polkadot full releases and commit there. The preference is not to commit anything directly to `main` moving forward.

Make the reserved branch stand out from the dev branches. Consider naming it `ci/latest-polkadot-full-release` to be self-explanatory

**Tasks**
- [x] Update [Frequency CI diagram](https://docs.google.com/drawings/d/1IcAzZbulRcntYQ5ub-zDyIkqJY1NE0iqClhkg2PE5lo)
- [x] Update `Check Polkadot Releases` workflow
- [x] Consider making `ci/*` branches protected
- [x] Verify that the 2/16 scheduled nightly CI run updated the recorded Polkadot release version in `ci/latest-polkadot-full-release` to `v0.9.37`
- [x] Remove `.github/workflows/misc/*` from `main` if present
- [ ] Verify that the 2/19 scheduled nightly CI run updated the recorded Polkadot release version in `ci/latest-polkadot-full-release` to `v0.9.37`

**Comment by wilwade** [comment]
@demisx I think protecting from deletion is all we need. So ✅
