### ISSUE TITLE
Integrate new benchmark self-hosted runner into CI

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#1100]
devOps have set up a new self-hosted benchmark runner for us. The runner can be targeted with `[self-hosted, Linux, X64, benchmark]`. Need to integrate it into GitHub actions and report back to the team.  

**Acceptance Criteria**
- [x] The benchmarks need to be triggered on-demand (Trigger TBD)
- [x] Only members of the LibertyDSNP org can trigger benchmark run
- [x] The benchmarks must run only on dedicated benchmark runners
- [x] The PR must be blocked from merging until updated weights have been recorded
- [x] Use `make benchmarks` for generating all weights
- [x] The results with updated weights must be committed back to the PR branch
- [x] The PR owner should be notified when the updated weights have been committed

**Tasks:**
- [x] Validate acceptance criteria with BC team
- [x] Collect feedback on the updated CI diagram
- [x] Implemente feedback
- [x] Implement workflow
- [x] Update Frequency CI diagram to add benchmark workflow
- [x] In PR comment, add link to the commit with updated weights.
- [x] Add instructions to Wiki on how to run benchmarks
- [x] Globally, replace hardcoded `git commit` with `stefanzweifel/git-auto-commit-action` action
- [x] Make "Run Benchmarks" check required after merging PR to `main`
- [x] Mark [Previous Benchmarking Flow Diagram (To Be Updated)](https://docs.google.com/drawings/d/1C_CyH5s7tzAlPTEYKClsSkdpSv95t5pHp_jdpLCt7ss/edit) as obsolete 

References:
- [Benchmarking Wiki](https://github.com/LibertyDSNP/frequency/wiki/Benchmarking)
- [Frequency CI diagram](https://docs.google.com/drawings/d/1IcAzZbulRcntYQ5ub-zDyIkqJY1NE0iqClhkg2PE5lo/edit)
- [Previous Benchmarking Flow Diagram (To Be Updated)](https://docs.google.com/drawings/d/1C_CyH5s7tzAlPTEYKClsSkdpSv95t5pHp_jdpLCt7ss/edit)
- #280
- [Manual Approval GH Action](https://github.com/marketplace/actions/manual-workflow-approval)
- [Block PR via commit status](https://docs.github.com/en/rest/commits/statuses)

**Comment by wilwade** [comment]
@demisx That looks good. I wonder if we want to dump some of the extra data from the output of the benchmark running into that PR comment, but either way 💯
