### ISSUE TITLE
Run CI jobs in container

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#1136]
Currently, we execute all jobs directly on self-hosted runners. This leads to a side effect where each runner has state left over from the previously executed job. We try to clean it up in the common "Reset Runner" action right now, but it has its own drawbacks:

1. It's a manual process, so it's easy to miss something 
2. Leftover state leads to intermittent errors which are hard to replicate and fix
3. The reset runner cannot be used as the first step, because the repo that hosts this runner needs to be checked out beforehand. And if the error is in the checkout action itself we are looking at catch 22 (ex. #1133)

In order to make CI process more reliable, I recommend considering running each job in a container, so each runner starts off with a clean state every single time. There is also another benefit of running in a container - we can create and use our own images with all preinstalled tools and libraries. Makes CI even faster.

**Tasks**:
- [x] Conduct research on running CI jobs in a container, caveats associated with it
- [x] Move shared runner jobs to container
- [x] Move self-hosted runner jobs to container
- [x] Remove debug steps
- [x] Delete test rust file
- [ ] Disable Reset Runner common action (globally)
- [ ] Remove `HOME: /root` env var?
- [ ] Evaluate the benefit of pre-building our own images with pre-installed tools and libs
- [ ] Switch from `root` to `runner` user

**References:**
- [Running jobs in a container](https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container)
- [Docker Container Jobs in GitHub Actions](https://josh-ops.com/posts/github-container-jobs/)
   - [Caveats of Running Jobs in CI Container](https://josh-ops.com/posts/github-container-jobs/#caveats)
- [Using Docker Containers In Jobs - GitHub Actions](https://dev.to/mihinduranasinghe/using-docker-containers-in-jobs-github-actions-3eof)
- [Docker run non root](https://github.com/creemama/docker-run-non-root)
