### ISSUE TITLE
Add Interval Sealing Option for No Relay Node

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1204]
As a developer working with Frequency, I would like to have a local system that allows me to simulate the blocks forming every `n` seconds. (empty is optional)

## Notes
- Add to the manual sealing mode an option that will trigger a block every `n` seconds
- Example: `frequency --dev --sealing=manual --sealing-interval 12 --sealing-allow-empty-blocks`

## ToDo
- [x] Make it work
- [x] Documentation in the readme
- [x] Documentation in the instant seal docker readme
- [x] Parameter to allow or disallow empty blocks (default either way)

**Comment by rlaferla** [comment]
How about just `--block-interval 12`?  If this argument is used, the interval to create a block is set to the number of seconds.  If the argument is not used, it defaults to manual sealing.  i.e.  There is no need for two CLI arguments.

**Comment by rlaferla** [comment]
How about --block-interval and --allow-empty-blocks?

**Comment by rlaferla** [comment]
Possible formats for the new CLI parameters:

```
--sealing="manual" --create-empty-blocks=false
--sealing="instant"
--sealing="timed" --interval=20 --create-empty-blocks=true
```
or perhaps:

`--sealing=20 --create-empty-blocks=true
`

**Comment by rlaferla** [comment]
Splitting this into two issues so we can test CI/build/test flow independent of the new mode.  https://github.com/LibertyDSNP/frequency/issues/1517
