### ISSUE TITLE
Test new build runners under k8s

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#1240]
Per @saisomepalle, there is a new build runner set up for testing under EKS. https://github.com/LibertyDSNP/frequency/settings/actions/runners.

Need to test and provide feedback. The runner can be targeted with `runs-on: [self-hosted, Linux, X64, testing]`.

![Screenshot 2023-03-15 at 9 51 25 AM](https://user-images.githubusercontent.com/4452412/225382328-45e2ac77-f2b6-4ac0-8f48-1e1f0632cec9.jpg)

**Tasks**
- [x] Verify "Verify PR" workflow (single runner)
- [x] Verify "Merge PR" workflow (single runner)
- [x] Verify "Release" workflow (single runner)
- [ ] Verify "Verify PR" workflow (scalable runners)
- [ ] Verify "Merge PR" workflow (scalable runners)
- [ ] Verify "Release" workflow (scalable runners)
