### ISSUE TITLE
Enable release workflow to enter release tag via UI

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#1277]
Simplify the release workflow further and let non-technical folks enter the release version directly into workflow UI window instead of tagging and pushing release version with git command. Let me know if you’d like me to add this feature leveraging this manual trigger approach:

https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

I think it’s going to be a matter of adding another trigger and perhaps, a release tag validation step. I believe everything else will be the same from that point on. I think it’s a good value-add, especially for non-technical folks

**Tasks:**
- [x] Update release workflow
- [x] Test various scenarious
- [x] Uncheck "Allow Deletions" in https://github.com/LibertyDSNP/frequency/settings/branch_protection_rules/33034218
- [x] Update[ Frequency CI diagram](https://docs.google.com/drawings/d/1IcAzZbulRcntYQ5ub-zDyIkqJY1NE0iqClhkg2PE5lo/edit)
- [x] Update [Release Process](https://github.com/LibertyDSNP/frequency/wiki/Release-Process) Wiki
