### ISSUE TITLE
Adjust release tag update logic

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#1304]
1. The `latest` git tag which purpose is to point to the latest full release has been moved to `precheck/cherry-v1.3.1` branch. Then, it failed to move to the new full release in https://github.com/LibertyDSNP/frequency/actions/runs/4576568388/jobs/8081775095. Update logic to ensure the `latest` tag update takes place for all full releases, regardless of what branch they were triggered from.
2. Rename `latest`tag to `_LATEST-FULL-RELEASE` to make it more obvious that this is a) reserved tag and b) it is supposed to point to full release only. 
3. GitHub tag protection rules are in beta right now. See if we can leverage this feature to lock in the release version tag once it’s been published on GitHub:
[https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-featu[…]managing-repository-settings/configuring-tag-protection-rules](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules)

**Assumptions:**

- A "locked release" is a release that has its assets published on GitHub releases page (point of no return)
- Once a release is locked, the same release tag cannot be reused. Any subsequent releases must have incremented number corresponding to the type of release (e.g major, minor, patch, rc#). 
- A release can be triggered from any branch as long as a deployer has access rights to push the release version tag to remote. 

**Tasks:**
- [x] Research protected tags in GitHub
- [x] Update workflow
- [x] Test latest tag being moved to `precheck/cherry-v0.0.1` branch
- [x] Test latest tag being moved to new `release-v*` branch
- [x] Move "Get previous full release tag" step to common action
- [x] Retest
- [ ] Merge PR
- [ ] Replace `latest` tag with _LATEST-FULL-RELEASE`

**Comment by wilwade** [comment]
@demisx I didn't realize tag protections were possible. Let's do that. I'll dm you the list of people who can create a release.
