### ISSUE TITLE
[Handles] Post Merge checklist

### ISSUE THREAD

**Issue by saraswatpuneet** [LibertyDSNP/frequency#1408]
**Misc TODO:**
- [x] #1392 renaming `delegator` across handles pallet to `msa_owner` for example in `claim_handle` `delegator_key` will become `msa_owner_key`
- [x] #1392 we should remove either display handle or full handle from the code base then and update the doc at the top of handles/src/lib.rs.
- [x] #1402 Move `pallets/handles/src/suffix.rs` into the handles_util package and add unit tests
- [x]  #1412 Add assert or remove if duplicate `test_full_handle_creation` in `pallets/handles/src/tests/handle_creation_tests.rs`
- [x] #1413 Check over replay tests and make sure they are testing the failure case when inside of 100 blocks. `test_handle_claim_replay_attack` does not. Some of these might be duplicates. See `pallets/handles/src/tests/handles_replay_attack_test.rs`
- [x] #1406 We use `into_bytes().try_into().unwrap()` in two places in the RPC. Change these so that they error instead of panic.
- [x] #1416
- [x] #1403 Add some reserved handles: `administrator` `mod` `moderator` `here` `channel`
- [x] We should be able to reset the counter if the min/max changes to allow for using the lower nth shuffled values of the new min/max
- [x] Replace SmallRng with a deterministic rng https://github.com/LibertyDSNP/frequency/issues/1407

**Low Priority TODO (Might be after merge):**
- [x] #1415
- [x] #1413 Move the `create_full_handle_for_index` and `create_full_handle` test helper functions into the `pallets/handles/src/tests/handle_creation_tests.rs` file
- [x] #1413 Update the `pallets/handles/src/tests/handle_creation_tests.rs` to follow table testing patterns
