### ISSUE TITLE
Upgrade Rust

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#1449]
Our Rust version is a bit out of date now. 

Last Polkadot release is using v1.68.2

We are still on 1.66 (CI) or 1.64 (asdf)

Likely should match to 1.68.2

## ToDo
- [x] Update asdf version
- [x] Update CI rust (or confirm it is on latest stable rust)
- [x] Update RUST_TOOLCHAIN (maybe?)
- [x] Update `rust-toolchain.toml`
- [x] Update Readme
- [ ] Update team (in slack)
- [ ] Update srtool image
- [ ] Look for other places to update
