### ISSUE TITLE
Create custom CI image

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#1467]
To limit the work required by each EKS runner, create a base custom CI image that can be pulled instead of `public.ecr.aws/lts/ubuntu:20.04`. 

- [x] The image should be based on ubuntu:20.04
- [x] The packages should be preinstalled
- [x] Ideally, we should create 1 base image that works for all jobs
- [x] The image should be uploaded to the GHCR and made available to CI
- [x] Place docker fille should be in `tools/ci/docker/ci-base-image.dockerfile` and rebuilt when the contents of this dir changes

**Tasks:**
- [x] Prep PR
- [ ] Merge PR
- [ ] Update [Frequency CI Diagram](https://docs.google.com/drawings/d/1IcAzZbulRcntYQ5ub-zDyIkqJY1NE0iqClhkg2PE5lo/edit) to add new CI base image jobs
- [ ] Make "Verify Node Docker Images" job required
