### ISSUE TITLE
Add Rust toolchain install to CI base image

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#1482]
Install Rust along with Toolchain in the base CI image and remove those steps from CI, correct

**Tasks**:
- [x] Add rust install to CI base image
- [x] Disable rust install toolchain in CI jobs where possible
- [x] Delete `1482-delete-me.rs` file

**Comment by p5150j** [comment]
ah.. @demisx .. if there were rust dev needs I set it as hi-prior so it wasn't blocking anything. Apologies.
