### ISSUE TITLE
Switch build jobs back to EKS runners

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#1595]
Per devOps comment in https://www.pivotaltracker.com/story/show/185045683.

**Tasks:**
- [x] Make workflow changes
- [x] Test all jobs in Verify PR workflow: https://github.com/LibertyDSNP/frequency/actions/runs/5260078454
- [x] Delete `runtime/1595-delete-me.rs`
- [x] Submit PR for review
