### ISSUE TITLE
Tracking `rustfmt` unstable options

### ISSUE THREAD

**Issue by mattheworris** [LibertyDSNP/frequency#1895]
This is a tracking issue for `rustfmt` features that should be stabilized.
Frequency.xyz currently uses these features and therefore requires a `nightly` version. 
When these options are stabilized, we can remove our dependence on `nightly`.

- [ ] https://github.com/rust-lang/rustfmt/issues/4991
- [ ] https://github.com/rust-lang/rustfmt/issues/3363
- [ ] https://github.com/rust-lang/rustfmt/issues/3367
- [ ] https://github.com/rust-lang/rustfmt/issues/3368
- [ ] https://github.com/rust-lang/rustfmt/issues/3373
- [ ] https://github.com/rust-lang/rustfmt/issues/3378
- [ ] https://github.com/rust-lang/rustfmt/issues/3379
