### ISSUE TITLE
[Governance]  Create and document chain upgrade process + requirements checklist

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/frequency#249]
Once the minimal level of governance and decentralization has been established, Determine and document the step by step process of how we would go about upgrading the chain

This assumes the broad process is:
Improvement Proposal Issue &rarr; Discussion in GitHub &rarr; PR(s) &rarr; GitHub tag and release &rarr; Proposal &rarr; Referendum &rarr; Voting &rarr; Enactment
    - **Update** This is basically the process.

### For these below, see the [Release](https://github.com/LibertyDSNP/frequency/wiki/Release) Process on the wiki. 
Manual QA is minimized as much as possible but detailed in the release process.
- [x] what additional tests, if any, are required to green-light a new GitHub release
- [x] what the release process looks like, i.e. how it's tagged and marked ready for release
- [x] is there any manual QA, and if so what is it?

### For these, see [Upgrading Runtime](https://github.com/LibertyDSNP/frequency/wiki/Upgrading-Runtime) on the wiki.
- [x] If using the referendum functionality, when and how to create the proposal on chain
- [x] What happens during enactment period

### For these,
- [x] How upgrades are announced and discussed in GitHub prior to any chain-level governance proposal (e.g. the GitHub issue, a DIP-NNN/DesignDoc, PRs associated with it)
- [x] How the changes are documented:  *in the Changelog*

We will be using Polkassembly ([Frequency Mainnet](https://frequency.polkassembly.io/), [Frequency Rococo](https://frequency-rococo.polkassembly.io/)) and the referenda process, combined with GitHub release process, and the changes are in GitHub and shown in the Changelog. Major changes will have the label ["change/major"](https://github.com/LibertyDSNP/frequency/issues?q=label%3Achange%2Fmajor+)

### Not needed:
- [x] any handoff process between BC team and DevOps

## TO Do/Decide
- [ ] Anything we need to do differently if a storage migration is required

**References:**
- [`v0.9.29->v0.9.30` Code upgrade example](https://github.com/LibertyDSNP/frequency/pull/744)

**Comment by shannonwells** [comment]
I started this as part of documenting governance planning and launch checklist

**Comment by shannonwells** [comment]
Closing as completed except for storage migration process, in a new Issuem [#918](https://github.com/LibertyDSNP/frequency/issues/918)
