### ISSUE TITLE
[Frequency] Launch checklist

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/frequency#254]
## Frequency Launch Primary Blockers
- [x] #339 
- [x] #379 

## Genesis
- [x] #347 
- [x] #264 
- [x] #623 
## Final Steps
- [x] #273 
- [x] #277 

## Non Blocking Launch Tracking
- [x] #255 
- [x] #268
- [x] #269

## Lower Level issues and tracking
- [x] [Mainnet Milestone](https://github.com/LibertyDSNP/frequency/milestone/24)
- [x] [Genesis Milestone](https://github.com/LibertyDSNP/frequency/milestone/29)
- [x] [Launch Features](https://github.com/LibertyDSNP/frequency/milestone/25)

**Comment by aramikm** [comment]
What about polkadot UI related changes to be able to see blocks & monitor network?
Monitoring infrastructure for Rococo (and later main-net)
