### ISSUE TITLE
[Final] Generate Genesis spec

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/frequency#273]
## Blocked by

- [x] #263
- [x] #264 
- [x] #270 
- [x] #271 
- [x] #347  
- [x] #272
- [x] #365 

## Tasks
- [x] Use srtooll to generate the mainnet production wasm
    - [x] Do this with a pair on two different machines to verify deterministic success
- [x] Generate the mainnet spec and use the wasm as the code value
- [x] Commit the spec file to `/resources/mainnet-frequency-genesis-spec.json`
- [x] Use [`load_frequency_spec`](https://github.com/LibertyDSNP/frequency/blob/d70911165395f71d17c0d6eb4e572daa5782d242/node/service/src/chain_spec/frequency.rs#L38-L40) to load up `mainnet-frequency-genesis-spec.json` and replace the contents of `pub fn frequency()` to use `load_frequency_spec`
- [x] Remove mainet spec generation (but not the WASM) from GitHub Actions
- [x] Remove mainnet as an option from `generate_specs.sh`
