### ISSUE TITLE
[DevOps] Enable running benchmarks on reference hardware for weight generation

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/frequency#280]
Requires @jacobmfoley assistance for infrastructure setup

Once reference hardware is decided we need to run our benchmarks on that hardware and update all the weights files.

Partially Blocked by:
- #279 
- #352 

## Expected
- Working with DevOps to get the Reference Hardware Spun Up
- The EC2 launch templates and the script to run benchmarks for all pallets will be developed in #279
- "Somehow" Trigger updating the weights on a branch
- Update runs weights on the reference hardware and commits back to the branch the updated weights
- User can then merge branch
- The benchmarks should be run against `--chain mainnet` spec per [this comment](https://github.com/LibertyDSNP/frequency/pull/355#discussion_r950123852)

## Acceptance Criteria
- [x] As a developer I should be able to request that the weights be run by entering `make benchmarks` in a PR comment
- [ ] As the repo, I should block merging until I must have the weights updated as the last commit if anything changes that might change the weight (rust files?)

## Tasks 
- [x] Contact @jacobmfoley to obtain AWS security credentials
- [x] Read Substrate material on benchmarking 
- [x] Set up local to run benchmarks 
- [x] Create a proposed solution diagram 
- [x] Collect and implement feedback on diagram
- [x] ~~Obtain `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` from @jacobmfoley  to access AWS from GitHub~~
- [x] Clarify instance on demand vs self hosted runner with @jacobmfoley 
- [x] Update diagram with the final approach

Blocked by:
- #377

## Helpful Links
- https://docs.substrate.io/main-docs/test/benchmark/
- https://medium.com/oak-blockchain/tutorial-benchmarking-for-parity-substrate-pallet-development-9cb68bf87ea2
- [Create AMI from instance](https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/tkv-create-ami-from-instance.html)
- [Create launch template](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-templates.html#create-launch-template)
- [Launch instance from a template](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-templates.html#launch-instance-from-launch-template)
- [Starting EC2 instance from Github Actions](https://aws.plainenglish.io/turn-on-aws-ec2-using-github-actions-a225820bbe9f)
- [Stopping EC2 instance from Github Actions](https://towardsaws.com/shutdown-aws-ec2-using-github-actions-769243af992b)
- [AWS Accounts](https://unfinished.awsapps.com/start#/)
- [Polkadot GitLab CI example](https://github.com/paritytech/polkadot/blob/master/.gitlab-ci.yml)

**Comment by wilwade** [comment]
@demisx I think we can just go with manual kickoff for now. We could likely create a glob that could do it, but then we would end up triggering it a lot of extra times.

**Comment by wilwade** [comment]
@demisx I think in general that looks good. I think the only thing I wonder is if it is worth blocking the dev branch from additional commits instead of just watching for additional commits and stopping the runner if it finds any. I think watching is better, but it might just be easiest to get up and running by not blocking or watching, but instead just fail out if when commit time comes if the head has changed.

PR blocking can happen via a Commit status API: https://docs.github.com/en/rest/commits/statuses

**Comment by wilwade** [comment]
@demisx One other thing. We should likely limit the commit to just LibertyDSNP org members. That way we can run them on forked PRs, but others cannot trigger it.

**Comment by wilwade** [comment]
> Do you mean limit running benchmarks to the LibertyDSNP org members only? In other words, parse the commit and ignore /run-benchmarks slash command in it unless this commit comes from one of the members.

Correct.

**Comment by wilwade** [comment]
> Great point. If understand correctly, you mean we can utilize the GitHub [concurrency group](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) here and have GH cancel running actions if newer commits are pushed to the same ref.

I wasn't sure if this was going to get kicked off as a GitHub action, but it it does, then that would work.

**Comment by jacobmfoley** [comment]
@demisx I've avoided adding AWS credentials to Github Actions and have the goal of eliminating all static IAM users  all together. 

If using actions is a requirement, we can run self hosted actions runners on the required instance sizes. 

If not, there is a spot fleet of Jenkins slaves with rust installed with the label "benchmark" ready to run jobs.

**Comment by wilwade** [comment]
@demisx Reference hardware is confirmed: #279

**Comment by wilwade** [comment]
Benchmarks are working via manual trigger with Jenkins.

Looking into self-hosted runners for it eventually: https://github.com/LibertyDSNP/frequency/issues/609

**Comment by wilwade** [comment]
https://github.com/LibertyDSNP/frequency/wiki/Benchmarking
