### ISSUE TITLE
Add Frequency to the SS58 Registry

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#365]
## Blockers
- [x] #302
- [x] Decimals: #263 
- [x] Final go ahead

## ToDo

- [x] PR for https://github.com/paritytech/ss58-registry
    - [x] https://github.com/paritytech/ss58-registry#process
    - [x] Add Frequency
- [x] Update the Chain Spec in frequency: https://github.com/LibertyDSNP/frequency/blob/a8aff2904bc3173606f63aa258ed36686a7bdc19/runtime/frequency/src/lib.rs#L195

```json
{
  "prefix": "90",
  "network": "frequency",
  "displayName": "Frequency",
  "symbols": ["FRQCY"],
  "decimals": ["8"],
  "standardAccount": "*25519",
  "website": "https://www.frequency.xyz"
}
```

**Comment by johnmela** [comment]
https://github.com/paritytech/ss58-registry/pull/144
