### ISSUE TITLE
Better Docker Files

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#372]
We need docker file(s) that are able to do the following:
- Instant sealing
  - `frequency-chain/instant-node`
  - Runs frequency in instant sealing mode for test containers or other testing situations
- Node:
  - `frequency-chain/node` or if we need two `frequency-chain/node` and `frequency-chain/rococo-node`
  - Runs a frequency mainnet/rococo node
  - this is close to what we have now

Optimizations to do:
- [ ] Smaller
    - [ ] Rather have multiple efficient docker images over one that can do it all
- [ ] Readme on Docker Hub
    - [ ] we have a new docker hub to setup for the chain: `frequency-chain`
    - [ ] I or Scott can switch over the GitHub Actions Docker Token env var when ready
- [ ] Better documentation for configuration and how to use it

**Tasks:**

- [x] Create `instant-seal-node` docker image
- [x] Switch to new [Docker Hub location](https://hub.docker.com/r/frequencychain/instant-seal-node)
- [ ] Create and publish `rococo-node` docker image
- [ ] Create and publish `mainnet-node` docker image
- [ ] Populate overview pages on Docker Hub
- [ ] Update README

References:
- [Polkadot Parachains](https://coinmarketcap.com/polkadot-parachains/polkadot/)
- [Multi-arch build and images, the simple way](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/)
- [Frequency Docker Hub](https://hub.docker.com/u/dsnp)
---
- [Moonbeam Docker Hub](https://hub.docker.com/u/purestake)
- [Moonbeam Docker files](https://github.com/PureStake/moonbeam/tree/master/docker)
- [Moonbeam publish docker workflow](https://github.com/PureStake/moonbeam/blob/master/.github/workflows/publish-docker.yml)
- [Moonbeam GitHub releases](https://github.com/PureStake/moonbeam/releases)
- [Moonbeam optimized binaries](https://docs.moonbeam.network/node-operators/networks/collators/faq/)
---
- [Astar GitHub releases](https://github.com/AstarNetwork/Astar/releases)
- [Astar Docker Hub](https://hub.docker.com/u/staketechnologies)
- [Astar release workflow](https://github.com/AstarNetwork/Astar/blob/master/.github/workflows/release.yml)
---
- [Acala GitHub releases](https://github.com/AcalaNetwork/Acala/releases)
- [Acala Docker file](https://github.com/AcalaNetwork/Acala/blob/master/scripts/Dockerfile)
- [Acala release workflow](https://github.com/AcalaNetwork/Acala/blob/master/.github/workflows/publish-release.yml)

**Comment by wilwade** [comment]
@demisx 

- Q1: There is just one right now, but we need two or perhaps three. Updated the issue description
- Q2: We have one, it is just under the dsnp name instead of frequency: https://hub.docker.com/r/dsnp/frequency CI pushes to it currently.

**Comment by wilwade** [comment]
A few notes:

1. While it would be nice to have `arm64` images, I don't think they are priority. (Not sure they are possible with standard GitHub Actions, but maybe)
2. We don't need a `relay-chain-validator-node` as that is just the [polkadot image](https://hub.docker.com/r/parity/polkadot).
3. `parachain-node` is not option 2 of the readme. It is for https://github.com/LibertyDSNP/frequency-docs/issues/10
4. If we can do either mainnet or rococo with the same image and just different configuration, the `parachain-node` setup works. However, I was hoping we could get a faster setup/smaller image for users if we have separate images for each network. (or just name it `node` as it would be basically the only one people should use. See below)
5. Naming. Here is how [Purestake](https://hub.docker.com/u/purestake), [Astar](https://hub.docker.com/u/staketechnologies), and [Acala](https://hub.docker.com/u/acala) name theirs. I think we want to find a pattern we like that is expressive but short is best.

**Comment by wilwade** [comment]
@demisx Sounds good. I think `mainnet-node` is fine if we have them split.

Really even if they combine, it might just be easier for tutorials and documentation to have them separate with different defaults.

**Comment by wilwade** [comment]
> The built images will copy necessary binary from the [Frequency release page artifacts](https://github.com/LibertyDSNP/frequency/releases)

Correct

> Each published image will be tagged with a version tag corresponding to the Frequency release version

Correct

> ...we aren’t providing a dev image in this issue that builds the chain from developer locally checked out repo (out of scope).

Correct. No building rust inside the image or in Docker.

**Comment by wilwade** [comment]
@demisx Create new ones. We'll end up deleting all the old releases likely once we have the final #282 and start doing real releases

**Comment by wilwade** [comment]
1. Shouldn't have to, but should be able to. Two different ones:
    - Frequency Rococo bootnodes
    - Rococo bootnodes.
2. I think we want to just use the built in spec, so we should not need a chain spec, just to define the chain as `frequency-rococo`.
    - MAYBE an option to push in a local file with the spec? Not sure how that would work, but it might be nice to be able to run off of a local spec file instead.
3. Correct.
4. Correct.

**Comment by wilwade** [comment]
> Just a heads-up. Strange thing I've noticed while configuring "Frequency Rococo - Dmitri" test network spec on OnFinality.io. Setting up the collator node spec doesn't have `--collator` in the list of the arguments:

@demisx I guess we will need to put that one in manually
