### ISSUE TITLE
[Chore] Optimizations to reduce size of binary files for Frequency

### ISSUE THREAD

**Issue by saraswatpuneet** [LibertyDSNP/frequency#429]
As of now Frequency does not take advantage of various rust semantics to generate targeted binaries which can also reduce size of frequency binary

**Todo**
- [x] Try enabling some [feature flags] for specific chain types like local/rococo/mainnet
- [x] Feature flags such as/for example ```--runtime-benchmarks``` are fashioned to only build binary with specific flag
- [x] Looks into Other optimization techniques such as but not limited to [min-sized-rust](https://github.com/johnthagen/min-sized-rust) and [this](https://arusahni.net/blog/2020/03/optimizing-rust-binary-size.html) etc.
- [x] Update jobs to generate binaries for rococo/mainnet separately via feature flags and other optimization techniques
