### ISSUE TITLE
Remove Unneeded Custom RPC calls

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#456]
Context: To make the code clearer, we want to have users use state queries instead of Custom RPCs for things that are a direct pass through with no logic or expected logic changes.

Remember: Custom RPCs allow for two things. 1. Off-chain logic and manipulation of data for easier use for the caller, 2. Consistent interface if the storage alters.

## Tasks
- [x] Remove Custom RPC [get_latest_schema_id](https://libertydsnp.github.io/frequency/pallet_schemas_rpc/trait.SchemasApiClient.html#method.get_latest_schema_id)
- [x] Remove Custom RPC [get_msa_id](https://libertydsnp.github.io/frequency/pallet_msa_rpc/trait.MsaApiClient.html#method.get_msa_id)
- [x] Update js/api-augment (custom rpcs are manual!)
- [x] Update example-client-frequency to use state queries
- [x] Notify other teams that might be using those RPCs

**Comment by rlaferla** [comment]
Which other teams are using those calls?  How are they notified?

**Comment by rlaferla** [comment]
Do we want to keep `get_by_schema_id()` and `check_schema_validity()`?  Only `get_latest_schema_id()`?

**Comment by wilwade** [comment]
> Do we want to keep `get_by_schema_id()` and `check_schema_validity()`? Only `get_latest_schema_id()`?

Correct. `get_by_schema_id` may do some additional work and `check_schema_validity` is off-chain and may also do more in the future.

**Comment by wilwade** [comment]
> Which other teams are using those calls? How are they notified?

I think it is just @pfrank13 in Slack and in the private channel in discord

**Comment by rlaferla** [comment]
`get_msa_id` appears to be identical to the api query `messageSourceIdOf`. Do we want to rename it, add an additional interface or change client code to use `messageSourceIdOf`?

**Comment by rlaferla** [comment]
Also, the RPC call `get_latest_schema_id()` takes a parameter: the block number/hash.

**Comment by rlaferla** [comment]
Notified @pfrank13
