### ISSUE TITLE
Add cargo audit to Verify PR Commit workflow

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#513]
[cargo-audit](https://github.com/RustSec/rustsec/tree/main/cargo-audit) audits Cargo.lock files for dependencies with security vulnerabilities. Please add it to the Verify PR Commit workflow so it runs on each PR commit verification. 

**Acceptance Criteria:**

- [x] Run cargo audit on each PR commit
- [x] Let cargo audit report errors and warnings as it does by default
- [x] Audit job should not be a required check in the Verify PR workflow
- [x] Do not auto-correct and auto-commit any fixes, it will be responsibility of the Rust developer. 

**Tasks:**
- [x] Add Cargo Audit job to Verify PR workflow
- [x] Run tests
- [x] Remove `513-...` test file(s)
- [x] Update [Frequency CI (v2)](https://docs.google.com/drawings/d/1IcAzZbulRcntYQ5ub-zDyIkqJY1NE0iqClhkg2PE5lo/edit) diagram

**Comment by wilwade** [comment]
@demisx I think we would need to fail, but not stop merge based on it. Perhaps instead of failing, it should just comment the results on the PR? Thoughts?
