### ISSUE TITLE
Small Rename Set

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#602]
## Todo

- [x] Event `SchemaRegistered` -> `SchemaCreated`
    - [x] Update Documentation
- [ ] Type `Provider` -> `ProviderId`
    - [ ] Update manual Types in `js/api-augment/definitions`
- [ ] Type `Delegator` -> `DelegatorId`
    - [ ] Update manual Types in `js/api-augment/definitions`
