### ISSUE TITLE
Renew Frequency PGP signing key (2023)

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#646]
As mentioned in #594, the Frequency PGP singing key is good for one year and will expire on 11/4/2023. We should renew this key prior to expiration, ideally some time in October 2023.

**Todo:**
- [x] Renew PGP signing key
- [x] Update GitHub secrets with the new private key
- [x] Test CI binary signing by creating a new test release following instructions in https://github.com/LibertyDSNP/frequency/wiki/Release-Process#create-test-release
- [x] Document renewal process in [PGP Wiki](https://github.com/LibertyDSNP/frequency/wiki/PGP)
- [x] Either reuse this issue or create a new issue for the next key renewal
- [x] Create new invitation in the Calendar for @wilwade @demisx @sbendar with due date at least 2 weeks prior to expiration
