### ISSUE TITLE
Integration Tests Checklist

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#692]
Milestone: https://github.com/LibertyDSNP/frequency/milestone/33

# Happy Path Each Extrinsic

## MSA Pallet
- [ ]  addPublicKeyToMsa(msaOwnerPublicKey, msaOwnerProof, newKeyOwnerProof, addKeyPayload)
  - [x] #695 
  - [ ] #694 
  - [x] #693 
- [ ]  create()
  - [x] #695 
  - [ ] #694 
  - [x] #693 
- [ ]  createProvider(providerName)
  - [x] #693 
- [ ]  createSponsoredAccountWithDelegation(delegatorKey, proof, addProviderPayload)
  - [ ] #694 
- [ ]  deleteMsaPublicKey(publicKeyToDelete)
  - [x] #695 
  - [ ] #694 
- [ ]  grantDelegation(delegatorKey, proof, addProviderPayload)
  - [x] #693 
- [ ]  grantSchemaPermissions(providerMsaId, schemaIds)
  - [x] #693 
- [ ]  retireMsa()
  - [x] #695 
  - [ ] #694 
- [ ]  revokeDelegationByDelegator(providerMsaId)
  - [x] #695 
  - [ ] #694 
- [ ]  revokeDelegationByProvider(delegator)
  - [x] #693 
- [ ]  revokeSchemaPermissions(providerMsaId, schemaIds)
  - [x] #695 
  - [ ] #694 

## Schemas Pallet
- [x] createSchema(model, modelType, payloadLocation)
- [x] #371 setMaxSchemaModelBytes(maxSize)

## Messages Pallet
- [ ] #696 addIpfsMessage(schemaId, cid, payloadLength)
- [ ] #697 addOnchainMessage(onBehalfOf, schemaId, payload)

# Happy Path State/RPC Queries

These might mostly be combined with the extrinsic tests

## Schemas Pallet
- [ ] #698
- [ ] #699

## MSA Pallet
- [ ] #701 publicKeyToMsaId(AccountId32)
- [ ] #701 publicKeyCountForMsaId(u64)
- [ ] #702 providerToRegistryEntry(u64)
- [ ] #703 RPC: msa_checkDelegations

## Messages Pallet
- [ ] #700

**Comment by wilwade** [comment]
Archive
