### ISSUE TITLE
Save Encoded Metadata from the latest built binary

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#715]
This metadata will be used by the Verify PR check as reference metadata to compare against to test for any metadata differences (diff metadata1.json metadata2.json) between the latest `main` commit and HEAD of PR branch. Can use ANY binaries as long as they are the same.

**TODO:**
- [x] Update the [Frequency CI Diagram](https://docs.google.com/drawings/d/1IcAzZbulRcntYQ5ub-zDyIkqJY1NE0iqClhkg2PE5lo/edit)
- [x] Collect feedback from @wilwade and @saraswatpuneet 
- [x] Implement new Job
