### ISSUE TITLE
Replace actions-rs/toolchain with rustup-toolchain-install

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#833]
Per [@wilwade's comment](https://github.com/LibertyDSNP/frequency/pull/828#discussion_r1054375892),  we should switch off of `actions-rs/toolchain` action to https://github.com/marketplace/actions/rustup-toolchain-install. It is actually maintained and looks like it is the go to replacement.

```rust
uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
```

**Tasks**:

- [x] Replace with new action in Verify PR workflow
- [x] Add new action to the authorized list in [Organization Settings](https://github.com/organizations/LibertyDSNP/settings/actions)
- [x] Collect feedback from @wilwade and @saraswatpuneet 
- [x] Replace with new action in the remaining workflows
- [ ] Delete test RS file
- [ ] Clean. up after test release
